### ISSUE TITLE
em_http_request 1.1.1 causes undefined method(@transaction not defined)

### ISSUE THREAD

**Issue by bhgames** [igrigorik/em-synchrony#169]
Hey,

When I did a bundle update, it force updated my em_http_request 1.1.0 to 1.1.1, and I started to see this error whenever I created or saved any active record object:

NoMethodError: undefined method `[]' for nil:NilClass
from /home/jprince/.rvm/gems/ruby-1.9.3-p429/bundler/gems/em-synchrony-d775d5638cd1/lib/em-synchrony/activerecord.rb:71:in`current_transaction'

I checked the code and it looks as if @transaction is nil. 

Is there anything else you need? Just make an active record object using em_http_request 1.1.1 + em-synchrony.

**Comment by dgutov** [comment]
While 1.0.4 plainly refuses to work with ActiveRecord 3.2, 1.0.3 seems to work, more or less, but spuriously fails the transactions example (about 50% of the time on my machine), no matter which version of `mysql2` is used:

```rb
Failures:

  1) Fiberized ActiveRecord driver for mysql2 transactions should work properly
     Failure/Error: widget.title.should eq('hello')
       
       expected: "hello"
            got: "hi14"
       
       (compared using ==)
     # ./spec/activerecord_spec.rb:103:in `block (5 levels) in <top (required)>'
     # ./spec/activerecord_spec.rb:102:in `each'
     # ./spec/activerecord_spec.rb:102:in `block (4 levels) in <top (required)>'
     # ./lib/em-synchrony.rb:38:in `block (2 levels) in synchrony'
```
